---
- name: Install ansible and all in L-FW
  hosts: test

  vars:
    ansible_cfg: /opt/ansible/REGION/FILES/ansible.cfg
    ansible_hosts: /opt/ansible/REGION/FILES/hosts
  tasks:
    - name: install epel-release
      dnf: name=epel-release state=installed
    
    - name: install ansible
      dnf: name=ansible state=installed
 
    - name: cp
      copy: src={{ ansible_cfg }} dest=/etc/ansible/ansible.cfg

    - name: cp
      copy: src={{ ansible_hosts }} dest=/etc/ansible/hosts
