---
- name: Install ansible and all in L-FW
  hosts: test

  vars:
    ansible_play: /opt/ansible/REGION/TASKS/ping.yml
  tasks:
    - name: cp
      copy: src={{ ansible_play }} dest=/etc/ansible/

    - name: sed for L-FW
      shell: sed -i "s/all/left/g" /etc/ansible/ping.yml
      when: inventory_hostname == "L-FW"

    - name: sed for R-FW
      shell: sed -i "s/all/right/g" /etc/ansible/ping.yml
      when: inventory_hostname == "R-FW"

    - name: left ansible start
      shell: ansible-playbook /etc/ansible/ping.yml
      register: leftout
      when: inventory_hostname == "L-FW"

    - name: right ansible start
      shell: ansible-playbook /etc/ansible/ping.yml
      register: rightout
      when: inventory_hostname == "R-FW"

    - name: left log
      local_action: copy content={{ leftout.stdout }} dest=/opt/ansible/REGION/LOGS/LEFT/ping.log
      when: inventory_hostname == "L-FW"    

    - name: rigth log
      local_action: copy content={{ rightout.stdout }} dest=/opt/ansible/REGION/LOGS/RIGHT/ping.log
      when: inventory_hostname == "R-FW"

