---
- name: test create CA
  hosts: L-FW

  vars:
    ansible_play: ./test_create_ca.yml
  tasks:
    - name: cp
      copy: src=./test_create_ca dest=/etc/ansible/

    - name: left ansible start
      shell: ansible-playbook /etc/ansible/test_create_ca.yml
      register: leftout
